# Generated by Django 3.1.3 on 2020-11-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_xplorer', '0002_interviewresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresource',
            name='owner',
        ),
    ]
