# Generated by Django 3.1.3 on 2020-11-18 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intern_xplorer', '0003_remove_interviewresource_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresource',
            name='category',
            field=models.CharField(choices=[('Data structures', 'Data structures and algorithms'), ('Programming languages', 'Programming languages'), ('System design', 'System design'), ('Databases', 'Databases'), ('Mobile development', 'Mobile development'), ('Computer networks', 'Computer networks'), ('Operating systems', 'Operating systems'), ('Data science', 'Data science'), ('Frontend developmnet', 'Frontend development'), ('Backend development', 'Backend development'), ('QA', 'QA'), ('Other', 'Other')], default='Other', max_length=21),
        ),
        migrations.AddField(
            model_name='interviewresource',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
