# Generated by Django 3.1.3 on 2020-11-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_xplorer', '0005_auto_20201118_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresource',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
