# Generated by Django 3.1.3 on 2020-11-18 16:37

from django.db import migrations, models
import intern_xplorer.models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_xplorer', '0006_auto_20201118_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresource',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=intern_xplorer.models.get_upload_location),
        ),
    ]
