# Generated by Django 3.1.3 on 2020-11-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_xplorer', '0007_jobposting'),
        ('intern_xplorer', '0007_auto_20201118_1637'),
    ]

    operations = [
    ]
