# Generated by Django 3.1.3 on 2020-11-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_xplorer', '0007_auto_20201118_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate'), ('recruiter', 'Recruiter')], default='student', max_length=10),
        ),
    ]
