# Generated by Django 3.1.3 on 2020-11-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern_xplorer', '0008_merge_20201119_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(default=None, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='logo',
            new_name='logo_url',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='user',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='intern_xplorer.company'),
        ),
    ]
