# Generated by Django 3.1.3 on 2020-11-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_xplorer', '0009_auto_20201119_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(default=None, null=True),
        ),
    ]
