# Generated by Django 3.1.3 on 2020-11-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern_xplorer', '0009_jobposting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(default=None, null=True)),
                ('website', models.URLField(default=None, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='user',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='role',
            field=models.CharField(default='Software Engineer', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='intern_xplorer.company'),
        ),
    ]
