# Generated by Django 3.1.3 on 2020-11-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_xplorer', '0010_auto_20201119_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobPosting',
            new_name='JobPost',
        ),
    ]
