# Generated by Django 3.1.3 on 2020-11-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_xplorer', '0011_auto_20201119_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='category',
            new_name='job_category',
        ),
    ]
