# Generated by Django 3.1.3 on 2020-11-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_xplorer', '0012_auto_20201119_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='how_to_apply',
            field=models.CharField(choices=[('Email', 'Email'), ('Company website', 'Company website')], max_length=60),
        ),
    ]
