# Generated by Django 3.1.3 on 2020-11-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_xplorer', '0014_auto_20201119_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresource',
            name='category',
            field=models.CharField(choices=[('Data structures and algorithms', 'Data structures and algorithms'), ('Programming languages', 'Programming languages'), ('System design', 'System design'), ('Databases', 'Databases'), ('Mobile development', 'Mobile development'), ('Computer networks', 'Computer networks'), ('Operating systems', 'Operating systems'), ('Data science', 'Data science'), ('Frontend development', 'Frontend development'), ('Backend development', 'Backend development'), ('QA', 'QA'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
